# Generated by Django 2.1.3 on 2018-11-20 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('model', models.CharField(choices=[(1, 'Ford'), (2, 'AUDI')], default=1, max_length=2)),
                ('car_type', models.CharField(max_length=20)),
                ('available', models.BooleanField()),
            ],
        ),
    ]
