# Generated by Django 2.1.3 on 2018-11-20 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lanza_car_sharing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='color',
            field=models.CharField(choices=[('RED', 'Red'), ('WHITE', 'White'), ('BLUE', 'Blue')], default='WHITE', max_length=5),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(choices=[('1', 'Ford'), ('2', 'AUDI')], default='1', max_length=2),
        ),
    ]
