# Generated by Django 2.1.3 on 2018-11-20 16:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lanza_car_sharing', '0002_auto_20181120_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='registered_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_type',
            field=models.CharField(choices=[('SEDAN', 'Sedan'), ('TURISMO', 'Turismo')], default='SEDAN', max_length=10),
        ),
    ]
