# Generated by Django 2.1.3 on 2018-11-20 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lanza_car_sharing', '0003_auto_20181120_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='car',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='car',
            name='facebook',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='car',
            name='location',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='color',
            field=models.CharField(choices=[('RED', 'Red'), ('WHITE', 'White'), ('BLUE', 'Blue'), ('BLACK', 'Black')], default='WHITE', max_length=5),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(choices=[('FRD', 'Ford'), ('AUD', 'AUDI'), ('VW', 'Volkswagen')], default='1', max_length=3),
        ),
    ]
