# Generated by Django 2.1.3 on 2018-11-21 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lanza_car_sharing', '0004_auto_20181120_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='car',
            name='remark',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
