# Generated by Django 2.1.3 on 2018-12-11 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvapp', '0031_auto_20181211_1852'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cv',
            field=models.ManyToManyField(to='cvapp.CV'),
        ),
    ]
