# Generated by Django 2.1.3 on 2018-11-16 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
