# Generated by Django 2.1.3 on 2018-11-16 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0002_note_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='owner_name',
            field=models.TextField(null=True),
        ),
    ]
