# Generated by Django 2.1.3 on 2018-12-01 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cvapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cv',
            old_name='cv_types',
            new_name='cv_type',
        ),
        migrations.RenameField(
            model_name='cv',
            old_name='second_name',
            new_name='last_name',
        ),
    ]
