# Generated by Django 2.1.3 on 2018-12-02 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvapp', '0002_auto_20181201_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='birth_year',
            field=models.DateField(blank=True, null=True, verbose_name='Birth Date'),
        ),
    ]
