# Generated by Django 2.1.3 on 2018-12-02 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvapp', '0003_cv_birth_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('started_date', models.DateField(blank=True, null=True, verbose_name='Start date')),
                ('finished_date', models.DateField(blank=True, null=True, verbose_name='Start date')),
            ],
        ),
        migrations.AlterField(
            model_name='cv',
            name='cv_lang',
            field=models.CharField(choices=[('English', 'English'), ('Polish', 'Polish'), ('Spanish', 'Spanish')], default='EN', max_length=3),
        ),
        migrations.AddField(
            model_name='cv',
            name='projects',
            field=models.ManyToManyField(to='cvapp.Project'),
        ),
    ]
