# Generated by Django 2.1.3 on 2018-12-02 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvapp', '0004_auto_20181202_1259'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('name',)},
        ),
        migrations.AddField(
            model_name='project',
            name='descr',
            field=models.TextField(blank=True, verbose_name='Project Description'),
        ),
        migrations.AddField(
            model_name='project',
            name='role',
            field=models.CharField(default='Provide project description', max_length=50),
            preserve_default=False,
        ),
    ]
