# Generated by Django 2.1.3 on 2018-12-02 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvapp', '0006_auto_20181202_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='facebook',
            field=models.URLField(blank=True, verbose_name='LinkedIn Profile'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='mobile',
            field=models.CharField(blank=True, max_length=12, verbose_name='Mobile'),
        ),
        migrations.AlterField(
            model_name='project',
            name='role',
            field=models.CharField(max_length=50, verbose_name='Role'),
        ),
    ]
