# Generated by Django 2.1.3 on 2018-12-02 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvapp', '0007_auto_20181202_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='cv_lang',
            field=models.CharField(choices=[('English', 'English'), ('Polish', 'Polish'), ('Spanish', 'Spanish')], default='EN', max_length=10),
        ),
    ]
