# Generated by Django 2.1.3 on 2018-12-02 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvapp', '0008_auto_20181202_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='CV attachment'),
        ),
    ]
