# Generated by Django 2.1.3 on 2018-12-02 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cvapp', '0010_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('Location', models.CharField(
                    max_length=20, verbose_name='Location')),
            ],
        ),
        migrations.DeleteModel(
            name='Language',
        ),
        migrations.AddField(
            model_name='cv',
            name='current_location',
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to='cvapp.Location'),
            preserve_default=False,
        ),
    ]
