# Generated by Django 2.1.3 on 2018-12-02 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvapp', '0013_auto_20181203_0010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='location',
        ),
        migrations.AddField(
            model_name='location',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Country'),
        ),
    ]
