# Generated by Django 2.1.3 on 2018-12-03 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cvapp', '0014_auto_20181203_0012'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
    ]
