# Generated by Django 2.1.3 on 2018-12-03 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvapp', '0015_delete_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, max_length=50, null=True, verbose_name='Country')),
            ],
        ),
    ]
