# Generated by Django 2.1.3 on 2018-12-03 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvapp', '0016_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='location',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Location'),
        ),
    ]
