# Generated by Django 2.1.3 on 2018-12-03 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cvapp', '0017_location_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='location',
            new_name='remote',
        ),
    ]
