# Generated by Django 2.1.3 on 2018-12-03 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvapp', '0018_auto_20181203_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='remote',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
