# Generated by Django 2.1.3 on 2018-12-03 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvapp', '0020_remove_location_remote'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='remote_work',
            field=models.CharField(choices=[('REMOTE_READY', 'Remote Ready'), ('REMOTE_ONLY', 'Remote Only')], default='REMOTE_READY', max_length=20),
        ),
    ]
