# Generated by Django 2.1.3 on 2018-12-03 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvapp', '0021_cv_remote_work'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(blank=True, max_length=50, null=True)),
                ('degree', models.CharField(blank=True, max_length=20, null=True)),
                ('started_date', models.DateField(blank=True, null=True, verbose_name='Start date')),
                ('finished_date', models.DateField(blank=True, null=True, verbose_name='Start date')),
            ],
        ),
    ]
