# Generated by Django 2.1.3 on 2018-12-03 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cvapp', '0022_education'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ['start_date'], 'verbose_name_plural': 'Education'},
        ),
        migrations.RenameField(
            model_name='education',
            old_name='finished_date',
            new_name='finish_date',
        ),
        migrations.RenameField(
            model_name='education',
            old_name='started_date',
            new_name='start_date',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='finished_date',
            new_name='finish_date',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='started_date',
            new_name='start_date',
        ),
    ]
