# Generated by Django 2.1.3 on 2018-12-03 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvapp', '0023_auto_20181203_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='description',
            field=models.TextField(blank=True, default='{}', null=True, verbose_name='Description'),
        ),
    ]
