# Generated by Django 2.1.3 on 2018-12-04 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvapp', '0028_auto_20181204_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='education',
            field=models.ManyToManyField(to='cvapp.Education'),
        ),
    ]
