# Generated by Django 2.1.3 on 2018-12-07 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvapp', '0029_cv_education'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cv_source_data', models.TextField(blank=True, null=True, verbose_name='CV Source Data')),
            ],
        ),
    ]
