# Generated by Django 2.1.3 on 2018-12-11 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvapp', '0030_rawdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawdata',
            name='cv_source_data',
            field=models.TextField(blank=True, default=' \n \n \nMarcin \nRoszczyk\n \n \nSolution Architect \n \n& Software Engineer\n \n \nmr@marcinr\nos\n.net\n \n \n \n \nPL +48537699001\n \n \n \n \n \n \nTechnolog\ny Competencies\n \nFull\n-\nstack \nDev\n, \nData Analysis, ML, ETL, \nMobile & Web Apps\n \n<\nlanguages\n>\n \n \n \nPython, Java\n \nS\ncript, SQL\n \n \n<\ndata\n \nprocessing\n>\n \n \nTensorflow, Elastic\nsearch,\n \nNiFi, Hadoop\n \n \n<\nfront\n-\nend ]\n>\n \n \nReact\nJS\n,\n \nBootstrap\n,\n \nCordova\n \n \n<\nweb\n \nframework\n>\n \n \nDjango, Flask\n \n \n<\ndata\n \nstore\n>\n \nPostgres, Oracle, OrientDB, Redis\n \n \n<\ninfrastr\nucture\n>\n \nLinux Ubuntu, Google Cloud, AWS, \nDocker\n \n \n<solutions>\n \nH\nW/SW HA/DR \ninfrastructure \ndesign, \nsizing for \nlarge scale solutions enterprise solutions\n \n \n<\nmethods\n>\nAgile/scrum, Test Driven Development, waterfall, \nfull software cycle development, Solution Architecture (Open \nGroup Certification)\n, ITIL Certification, requirements analysis, \nUML \n\n \ndiagraming & documentation\n \n<\n/\n>\n \nProfile & Business \nExperience \n \nBlend of strong technical and \nbusiness skills\n \nOver 10 years of experience in \nmultiple sectors telco, banking, \nretail\n \nGDPR/RODO, mobile apps, CRM, \nlogistics and stock mgmt., Order \nManagement, Product Catalogue \n \nWorked with top\n-\ntier clients \n(IKEA, Omantel, ABB, PKO BP \nand more) \n \nCreated start\n-\nups: sensID \nsoftware\n \n \nRecent Projects\n \nGDPR \nP\nersonal \nD\nata \nClassification\n \nSensID Software \n2017/2018 \nArchitect/\nPython \nDeveloper\n \n \n \nMobile App for customer care and service management \n \nOmantel Telecom 2018 Solution Architect/Java Script \nDeveloper\n \n \nData Warehouse/\nETL/\nData Lake \nimplementation\n \nOmantel\n \n2015/2016 SolutionArchitect/Software Engineer\n \nGlobal Inventory & Order management Application Integration\n \nIKEA \n2014/2015\n \nSolution Architect\n \n \nFormal education:\n \nMsC in Computer Systems and \nNetworks \n-\n \nWroclaw University \nof Technology\n \n \nMaster of Business and \nAdministration \n\n \nWarwick  \nBusiness School        \n \n                        \n \nPrevious employment\n:\n \n2015\n/\n2017 Tuatara\n \n2003/2015 \nIBM \n \n2002\n-\n2003 \nPwC/\nSofrecom \n \n2000\n-\n2002 \nCGI\n \n \n', null=True, verbose_name='CV Source Data'),
        ),
    ]
